### ISSUE TITLE
Wrong article count

### ISSUE THREAD

**Issue by hasanmerkit** [v17development/flarum-support-feedback#12]
![image](https://user-images.githubusercontent.com/18331715/191080934-27d5c8e6-654a-4daa-9201-b9c2e3a50888.png)

**Comment by hasanmerkit** [comment]
Demo available: https://www.teteos.net/knowledgebase

**Comment by jaspervriends** [comment]
This is due to the Flarum tag discussion counter unfortunately. 

We could try adding a button to 're-count discussions' in a tag. That might could help. What do you think?

**Comment by hasanmerkit** [comment]
Adding "Re-count discussions" feature is very good idea. I think this button helps to users have old and big databases like me.
I temporary hidded using ".MoreArticles{display:none!important;}" css code.

**Comment by jaspervriends** [comment]
Fixed in next version
