### ISSUE TITLE
Conflict with fof/gamification

### ISSUE THREAD

**Issue by hackeresq** [v17development/flarum-support-feedback#14]
I've noticed a weird issue when I have the fof/gamification extension enabled. I find that the layout for tickets is destroyed:

<img width="1058" alt="Screenshot 2023-12-04 at 10 32 01 PM" src="https://github.com/v17development/flarum-support-feedback/assets/16628119/b30b52c4-1f6a-44d3-b21d-ec263e2c7690">

Here's the console errors (side note: it was the call to `ranks` that tipped me off this was related to gamification):

<img width="616" alt="Screenshot 2023-12-04 at 10 32 09 PM" src="https://github.com/v17development/flarum-support-feedback/assets/16628119/8b7ef570-375a-4176-90fc-90d221ef6921">

For now I've disabled fof/gamification which is fine, but hopefully this can resolved?

**Comment by jaspervriends** [comment]
Hey there, thanks for reporting this issue! We'll work on a update later in December/start of January soon! If we need any further information, we'll let you know!

In the meantime, if you have any further feedback, make sure to let us know!

**Comment by hackeresq** [comment]
Closing this here. This is actually a fof/gamification issue.
